### ISSUE TITLE
match table

### ISSUE THREAD

**Issue by schneefux** [vainglorygame/processor#1]
* [x] duration
  * [x] gameMode
  * [x] patchVersion
  * [x] shard
  * [x] result
  * [x] queue
  * [ ] anyAFK
  * [ ] winningTeam
  * [ ] krakenCaptures
  * [ ] laneMinionsSlayed
  * [ ] jungleMinionsSlayed
  * [ ] heroDeaths

**Comment by kvahuja** [comment]
this is redundant given the new web schema. the raw and web have everything that API gives
