### ISSUE TITLE
processor for participants -> match_participation breaks due to an error for integer type

### ISSUE THREAD

**Issue by kvahuja** [vainglorygame/processor#12]
maybe it's the API data, but since yesterday after the API was refreshed the specific transformation query breaks and gives the following error:
```
File "/usr/local/lib/python3.5/asyncio/futures.py", line 293, in result
  raise self._exception
yncpg.exceptions.InvalidTextRepresentationError: invalid input syntax for integer: ""
```

> when we run the query as is in pgAdmin we get the same error.

I changed the code in the processor to add some exception handling as part of #11. the processor doesn't crash and shows the record which is invalid as below. However, i get only 50 records in the Web-> match_participation table. 

```
processor_1              | ERROR:root:rec: <Record participant_id='663ce045-f409-11e6-bf96-0242ac11002d' player_id='6dbdb38e-d4b8-11e5-a7d4-06f4ee369f53' rosterId=0 fk_player_id=0 fk_ma
tch_results_id=0 hero='*Joule*' kills=3 deaths=2 assists=3 KD=Decimal('0.0') KDA=Decimal('0.0') killParticipation=0 laneMinionsSlayed=2 jungleMinionsSlayed=13 turretsDestroyed=0 krakenC
aptures=0 goldMineCaptures=0 crystalMineCaptures=1 wentAfk=0 perfectGame=False>
```

**Comment by schneefux** [comment]
It's probably because Battle Royale doesn't have krakenCaptured etc.
`kills` is sometimes `''` too, maybe it's called differently in Blitz.
Until vainglorygame/apigrabber/issues/23 is fixed, I will work around the issue with `NULLIF` checks.

**Comment by kvahuja** [comment]
damn it Blitz/BR. LOL

**Comment by kvahuja** [comment]
seems like this should be fixed. i will check and update

**Comment by schneefux** [comment]
reopen if still relevant
