### ISSUE TITLE
Setup Relationships (properly) via processor

### ISSUE THREAD

**Issue by kvahuja** [vainglorygame/processor#15]
What i have done till now is basically gets us the data from 1 rec to another, but it's really not setup using the DB relationships that we need. 

Current approach is to
1. Get Match (by id or player search but we start with a match ID)
2. Based on that Match, we make another call to get "Roster" aka teams
3. once we have the team, we then need to use the roster ID and find the participants aka players in the match
4. participant table gives us a Player ref and we use that to get player attributes like names, level etc.

this flow works well if the starting point is a match and we are going further down the funnel. however, the flow we are going to be working starts on the very opposite end aka the players. so we have to start with

1. Find a player - this gives us only a player ref and nothing else. as per the model this is lowest possible node available to us.
2. Find all matches - now we dont have a direct relationship between the two. to make matters worse the relationship flows across 2 tables - player -> participant -> roster -> match
3. So we find all records in participant which has a player ID ref
4. now get a roster based on roster ID for the participant id we have with us. the issue is we are going bottom up and in the API, when we get a participant we dont get a roster. so for us the ID we have, we have to now send this to the parent
5. ... you get the idea... 

so if we can update our processor layer to setup relational models (say)...
Match : Roster :: One to Many

currently, in match table I have roster_1 and roster_2 which allows me to fetch the data. however, we need a match_apiId column in roster table which holds the matchId. this way we can:
```SQL
select * from roster where match_apiId = "1922b51c-f65a-11e6-bf59-02e172e58227" where match_id is the actual value)
````
and we will get all matches with their proper rosters.

today I believe we can run following but it's not ideal:
```SQL
select * from roster where "apiId" in (select roster_1 from match  where "apiId" = '1922b51c-f65a-11e6-bf59-02e172e58227' 
                                       union 
                                       select roster_1 from match where "apiId" = '1922b51c-f65a-11e6-bf59-02e172e58227') ```

**Comment by schneefux** [comment]
Make a wish!
With #22, we can get references from roster->match and everything you can think of easily.

**Comment by schneefux** [comment]
reopen on meta if still relevant
