### ISSUE TITLE
match result table

### ISSUE THREAD

**Issue by schneefux** [vainglorygame/processor#2]
* [ ] team
  * [ ] winner
  * [ ] surrender
  * [ ] teamSize
  * [ ] hero_1
  * [ ] hero_2
  * [ ] hero_3
  * [ ] laneMinionsSlayed
  * [ ] jungleMinionsSlayed
  * [x] turretsDestroyed
  * [x] kills
  * [ ] assists
  * [ ] deaths
  * [x] krakenCaptures
  * [ ] goldMineCaptures
  * [ ] crystalMineCaptures
  * [ ] afkCount
  * [ ] afkTime

**Comment by kvahuja** [comment]
this is redundant given the new web schema. the raw and web have everything that API gives
