### ISSUE TITLE
match participation table

### ISSUE THREAD

**Issue by schneefux** [vainglorygame/processor#3]
* [x] player_id
  * [ ] rosterId
  * [ ] fk_player_id
  * [ ] fk_match_results_id
  * [x] hero
  * [x] kills
  * [x] deaths
  * [x] assists
  * [ ] kd
  * [ ] kda
  * [ ] killParticipation
  * [x] laneMinionsSlayed
  * [x] jungleMinionsSlayed
  * [x] turretsDestroyed
  * [x] krakenCaptures
  * [x] goldMineCaptures
  * [x] crystalMineCaptures
  * [x] wentAfk
  * [ ] perfectGame

**Comment by kvahuja** [comment]
this is redundant given the new web schema. the raw and web have everything that API gives
