### ISSUE TITLE
player table

### ISSUE THREAD

**Issue by schneefux** [vainglorygame/processor#4]
* [x] apiId
  * [x] name
  * [x] level
  * [x] xp
  * [x] played
  * [x] playedRanked
  * [ ] totalGamePlaytime
  * [x] wins
  * [x] streak
  * [ ] herosUnlocked
  * [ ] skinsUnlocked
  * [x] lifeTimeGold
  * [ ] lifeTimeKills
  * [ ] lifeTimeDeaths
  * [ ] lifeTimeAssists
  * [ ] lifeTimeKD
  * [ ] lifeTimeKDA

**Comment by kvahuja** [comment]
this is redundant given the new web schema. the raw and web have everything that API gives
