### ISSUE TITLE
When run from start, processor injects duplicate entries into WEB table

### ISSUE THREAD

**Issue by kvahuja** [vainglorygame/processor#8]
i dont know teh exact use case, but it seems if the script stops in between (doesn't have a clean finish) it ends up injecting dupes into Web DB.

i know what we had was development, but wanted to capture my observation (in case).

**Comment by schneefux** [comment]
https://github.com/vainglorygame/processor/pull/7#issuecomment-279627409
It injects duplicates on every run, so far there is no check whether an object has been processed or not. Working on it, next thing to do :)
